### ISSUE TITLE
Device supported traits

### ISSUE THREAD

**Issue by i8beef** [actions-on-google/smart-home-schema#1]
First, thank you thank you thank you.

Second, selfish ask, is there any chance of getting a device schema description of some sort that would give a mapping of device types to supported traits? I have a little script I use to generate a mapping for my app, but being able to use a structured document from here would be so much easier than trying to parse the HTML structures reliably.

**Comment by i8beef** [comment]
Hmmm fair enough. How about just a list of supported device types then somewhere? The INTENTS seem to only be examples, so I'm guessing something like the SYNC intent wouldn't be the right place to put these as options... but it would be useful to be able to get a full list of support device types from here if we could!

**Comment by proppy** [comment]
@i8beef sorry for the delay, we push some metadata for device types examples here:
https://github.com/actions-on-google/smart-home-schema/tree/master/types

But your originally suggestion is still valid, ideally we would have an `enum` of traits / device types somewhere in the platform schema.

**Comment by i8beef** [comment]
Yes, that's awesome! Thank you. The enum would be a nice to have, but what you've provided there is gonna provide me with something to really play with to generate validations and command response building! You can close this if you want!

**Comment by i8beef** [comment]
Note, I've been playing with this a bit. The biggest hole I see right now is indeed the lack of a comprehensive list of traits / command strings. I can rip the device types form the YAML files, and played with just taking a unique list of trait / command types from those files, but there are several that have no representation in those files, so that doesn't give me the ability to generate complete enum lists for these.

It gets me close... in fact if the missing traits / command examples were just added to the YAML files, I'd be golden... though I kinda thing since traits aren't "connected" to device types as you said above, an actual equivalent "traitType" YAML would fit better to supply the trait definitions (Bonus: with the Name from the All traits" page would be sweet too... 😄 ). I was just thinking this would be better than, or a great ADDITION to, just putting the enum values into the schema validation.

Missing traits: 

- action.devices.traits.LightEffects
- action.devices.traits.Locator
- action.devices.traits.Rotation
- action.devices.traits.SoftwareUpdate

Missing commands:

- action.devices.commands.BrightnessRelative
- action.devices.commands.ColorLoop
- action.devices.commands.EnableDisableGuestNetwork
- action.devices.commands.GetGuestNetworkPassword
- action.devices.commands.GetGuestNetworkPassword
- action.devices.commands.HumidityRelative
- action.devices.commands.Locate
- action.devices.commands.mediaRepeatMode
- action.devices.commands.mediaSeekRelative
- action.devices.commands.mediaSeekToPosition
- action.devices.commands.mediaShuffle
- action.devices.commands.OpenCloseRelative
- action.devices.commands.Reverse
- action.devices.commands.SetFanSpeedRelative
- action.devices.commands.Sleep
- action.devices.commands.SoftwareUpdate
- action.devices.commands.StopEffect
- action.devices.commands.TemperatureRelative
- action.devices.commands.volumeRelative
- action.devices.commands.Wake

Thank you, I actually got a lot of good use our of these schema files!

**Comment by proppy** [comment]
> Edit: Also FYI, I think either the "setChannel" examples in the tv, settop, and remotecontrol example.yaml files is wrong (Using "SelectChannel" capital "S"), or the documentation (https://developers.google.com/assistant/smarthome/traits/channel#action.devices.commands.selectchannel) has the incorrect capitalization specified.

Fixed with https://github.com/actions-on-google/smart-home-schema/commit/06300d26ab82ae126edd7608c0d11b537d15ba2e :)

**Comment by casper2002casper** [comment]
> There is no explicit mapping here. Any trait can pretty much be attached to any device type. We do provide trait recommendations in the docs as there are certain traits that are most common for certain device use cases (example: Light + `Brightness`/`ColorSetting`), but those are not requirements nor do they express the limit of support for that device. If you declared a Light with `ArmDisarm`, the platform would support it.

The documentation on developers.google does mention required traits for some devices (for example:  [remotecontrol)](https://developers.google.com/assistant/smarthome/guides/remotecontrol)). However it says they are only required if your devices supports them, which sounds like they are optional. Do they devices need to support them to work, and if so could the required traits be added to this git?

**Comment by proppy** [comment]
@casper2002casper agreed that could be clearer, those hint are relevant to the "certification" part of the smarthome action launch process:
https://developers.google.com/assistant/smarthome/develop/launching

My understanding of the current wording is that "required" traits would only be required if the underlying device support the corresponding capabilities (where as recommended traits would be left to the implementer discretion)

We are currently working with the certifications team to make the process and requirements more transparent thru public documentation. /cc @ToniCorinne 

> And if so could the required traits be added to this git?

Currently we do have a list of traits in the examples metadata https://github.com/actions-on-google/smart-home-schema/blob/master/types/remotecontrol/examples.yaml but those are just "examples" and should not be considered representative of their requirements status.

We're planning to augment those with dedicated device metadata with the following fields:
 - name
 - shortname
 - description
 - availability
 - version
 - traits
   - recommended
   - required

and we're also eager to here from you what other metadata you would find useful as part of this repository, so keep the feedback coming :)

**Comment by proppy** [comment]
> The biggest hole I see right now is indeed the lack of a comprehensive list of traits / command strings.

We now have platform level enum schema for traits / commands / and device types, see:
https://github.com/actions-on-google/smart-home-schema/commit/06c11272f13bc1615452a9d5db4e67b4d007fb65

**Comment by i8beef** [comment]
I am happy with this. If you wish to close this, my needs are met unless there's other work you'd like to put under this ticket.

**Comment by proppy** [comment]
@i8beef I'd like to keep this open until we publish the YAML metadata referenced in https://github.com/actions-on-google/smart-home-schema/issues/1#issuecomment-758314281.

**Comment by proppy** [comment]
The device and traits YAML metadata have been added as part of https://github.com/actions-on-google/smart-home-schema/commit/c14725786d2aae0bc2de52cc38f8e716dfbe6c9e
